### ISSUE TITLE
Screenshots how it looks like at a theme

### ISSUE THREAD

**Issue by gino2014** [macopedia/magento2-omnibusdirective#1]
Hi,
maybe you could provide some screenshots how it looks like at the frontend (reviews and special prices) when the extension is working. 
Thanks in advance
Gino

**Comment by idziakjakub** [comment]
Hi @gino2014,

thanks for the suggestions! I updated README file and uploaded screenshots in section: https://github.com/macopedia/magento2-omnibusdirective#screenshots

Best regards
Jakub
